version: '3.8'

services:

  api:
    build: 
      dockerfile: ./Dockerfile
      context: ./backend/
    depends_on:
      - db
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "3000:3000"

  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
     - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
     - "5050:80"
    restart: always

volumes:
  database-data:
  pgadmin: