version: '3.8'

services:

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend/
    ports:
      - "8080:80"
    depends_on:
      - api
    
  api:
    build: 
      dockerfile: ./Dockerfile
      context: ./backend/
    depends_on:
      - db
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - API_PORT=${API_PORT}
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
  pgadmin: